-- =============================================
-- INSERT data for agent_platforms
-- Generated from Excel: Agents平台信息.xlsx
-- Date: 2026-05-12
-- =============================================

INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Kakobuy', 'kakobuy', 'https://nstatic.kakobuy.com/banner/202602/22/1080564df2b8f006455d32460b53b7d9.png', 'https://www.kakobuy.com', 'https://ikako.vip/r/sdv45', 'sdv45', ARRAY["Taobao", "1688", "Weidian"], 1, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Superbuy', 'superbuy', 'https://cdn.superbuy.com/starit-superbuy/dist/img/logo-first.png', 'https://www.superbuy.com', 'https://www.superbuy.com/cn/page/login/?partnercode=EH7LaP&type=register', 'EH7LaP', ARRAY["Taobao", "1688", "Weidian"], 2, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Oopbuy', 'oopbuy', 'https://oopbuy.com/static/img/logo.c6dbb71b.svg', 'https://oopbuy.com', 'https://oopbuy.com/register?inviteCode=V7WQVRFKE', 'V7WQVRFKE', ARRAY["Taobao", "1688", "Weidian"], 3, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Acbuy', 'acbuy', 'https://www.acbuy.com/favicon1.ico', 'https://www.acbuy.com', 'https://www.acbuy.com/login?loginStatus=register&code=X4U67L', 'X4U67L', ARRAY["Taobao", "1688", "Weidian"], 4, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Mulebuy', 'mulebuy', 'https://mulebuy.com/favicon-32x32.png', 'https://mulebuy.com', 'https://mulebuy.com/register?ref=201162142', '201162142', ARRAY["Taobao", "1688", "Weidian"], 5, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Allchinabuy', 'allchinabuy', 'https://www.allchinabuy.com/favicon.ico', 'https://www.allchinabuy.com', 'https://www.allchinabuy.com/cn/page/login?partnercode=EH7LZu&type=register', 'EH7LZu', ARRAY["Taobao", "1688", "Weidian"], 6, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('iTaobuy', 'itaobuy', 'https://www.itaobuy.com/assets/icon_logo@2x-xKGUKwGN.png', 'https://www.itaobuy.com', 'https://itaobuy.allapp.link/d81dud90b4mpqd4eqmdg', 'R3ZTA9EM', ARRAY["Taobao", "1688", "Weidian"], 7, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('USfans', 'usfans', 'https://media.usfans.com/images/iconWindow/20251202/6ebaf586041d4ff8ad34d66a35d3dc88.webp', 'https://usfans.com', 'https://usfans.com/register?ref=YDDH2R', 'YDDH2R', ARRAY["Taobao", "1688", "Weidian"], 8, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Hipobuy', 'hipobuy', 'https://hipobuy.com/static/favicon/32x32.png', 'https://hipobuy.com', 'https://hipobuy.com/register?inviteCode=WJJ658A4A', 'WJJ658A4A', ARRAY["Taobao", "1688", "Weidian"], 9, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Litbuy', 'litbuy', 'https://litbuy.com/static/img/logo.9dc463e0.png', 'https://litbuy.com', 'https://litbuy.com/register?inviteCode=JXT81I8DG', 'JXT81I8DG', ARRAY["Taobao", "1688", "Weidian"], 10, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Sugargoo', 'sugargoo', 'https://www.sugargoo.com/assets/logo-2-white-7e34e5ad.png', 'https://www.sugargoo.com', 'https://www.sugargoo.com/register?memberId=3351269556942664886', NULL, ARRAY["Taobao", "1688", "Weidian"], 11, true);
INSERT INTO agent_platforms (name, slug, logo_url, website_url, jump_url_template, site_promo_code, supported_sources, display_order, is_active) VALUES ('Hoobuy', 'hoobuy', 'https://cdn.static.hoobuy.com/favicon/favicon_32.ico', 'https://hoobuy.com', 'https://hoobuy.com?utm_source=website&utm_medium=ambassador&utm_campaign=linksharing&inviteCode=7EjOxnM8', '7EjOxnM8', ARRAY["Taobao", "1688", "Weidian"], 12, true);
